name: Links

on:
  pull_request:
    paths:
#      - '.github/workflows/links.yml' Temporarily disabled by @Stargator
      - 'concept/**/*.md'
      - 'concept/**/links.json'
      - 'docs/*.md'
#      - 'exercises/**/*.md' Temporarily disabled by @Stargator
      - 'reference/*.md'
      - '*.md'
      - '**/**/*.md'
      - '**/*.md'

  repository_dispatch:
  workflow_dispatch:

jobs:
  linkChecker:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: Link Checker
        uses: lycheeverse/lychee-action@885c65f3dc543b57c898c8099f4e08c8afd178a2
        with:
          args: --verbose --no-progress --require-https .
          fail: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
